// <auto-generated />
using System;
using LibretaSanitariaAPI.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibretaSanitariaAPI.Migrations
{
    [DbContext(typeof(LibretaDbContext))]
    [Migration("20260630012543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HistorialVeterinario", b =>
                {
                    b.Property<int>("HistorialesMedicosID")
                        .HasColumnType("int");

                    b.Property<int>("VeterinariosID")
                        .HasColumnType("int");

                    b.HasKey("HistorialesMedicosID", "VeterinariosID");

                    b.HasIndex("VeterinariosID");

                    b.ToTable("HistorialVeterinario");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Consulta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaTurno")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HistorialMedicoId")
                        .HasColumnType("int");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HistorialMedicoId");

                    b.HasIndex("MascotaId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.HistorialMedico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.Property<int>("TratamientoRealizado")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MascotaId");

                    b.ToTable("HistorialesMedicos");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Mascota", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DuenioId")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("QR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DuenioId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Recordatorio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MascotaId");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ID");

                    b.ToTable("Usuario");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Vacuna", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<int>("Dosis")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ConsultaId");

                    b.ToTable("Vacunas");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Duenio", b =>
                {
                    b.HasBaseType("LibretaSanitariaAPI.Modelos.Usuario");

                    b.HasDiscriminator().HasValue("Duenio");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Veterinario", b =>
                {
                    b.HasBaseType("LibretaSanitariaAPI.Modelos.Usuario");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaginaWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Veterinario");
                });

            modelBuilder.Entity("HistorialVeterinario", b =>
                {
                    b.HasOne("LibretaSanitariaAPI.Modelos.HistorialMedico", null)
                        .WithMany()
                        .HasForeignKey("HistorialesMedicosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibretaSanitariaAPI.Modelos.Veterinario", null)
                        .WithMany()
                        .HasForeignKey("VeterinariosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Consulta", b =>
                {
                    b.HasOne("LibretaSanitariaAPI.Modelos.HistorialMedico", "HistorialMedico")
                        .WithMany("Consultas")
                        .HasForeignKey("HistorialMedicoId");

                    b.HasOne("LibretaSanitariaAPI.Modelos.Mascota", "Mascota")
                        .WithMany("Consultas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibretaSanitariaAPI.Modelos.Veterinario", "Veterinario")
                        .WithMany("Consultas")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistorialMedico");

                    b.Navigation("Mascota");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.HistorialMedico", b =>
                {
                    b.HasOne("LibretaSanitariaAPI.Modelos.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Mascota", b =>
                {
                    b.HasOne("LibretaSanitariaAPI.Modelos.Duenio", "Duenio")
                        .WithMany("Mascotas")
                        .HasForeignKey("DuenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duenio");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Recordatorio", b =>
                {
                    b.HasOne("LibretaSanitariaAPI.Modelos.Mascota", "Mascota")
                        .WithMany("Recordatorios")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Vacuna", b =>
                {
                    b.HasOne("LibretaSanitariaAPI.Modelos.Consulta", "Consulta")
                        .WithMany("Vacunas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Consulta", b =>
                {
                    b.Navigation("Vacunas");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.HistorialMedico", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Mascota", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Recordatorios");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Duenio", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("LibretaSanitariaAPI.Modelos.Veterinario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
