/**
 * Post-processing for `drizzle-kit pull` (run by `npm run db:introspect`).
 * Works around drizzle-kit introspection bugs and keeps only schema.ts:
 *   - empty-string defaults come out as `.default(')`  → `.default('')`;
 *   - empty-array defaults (`'{}'`) come out as `.default([""])` → `.default([])`;
 *   - relations.ts is dropped: it duplicates keys when two FKs join the same
 *     tables, and the app uses explicit joins anyway;
 *   - a lint-disable header is added (generated code);
 *   - the SQL snapshot is dropped: supabase/migrations owns the schema.
 */
import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const dir = path.resolve(import.meta.dirname, "../src/lib/db/schema");
const schemaFile = path.join(dir, "schema.ts");

const HEADER =
  "/* eslint-disable */\n// Generated by `npm run db:introspect`. Do not edit by hand.\n";
const source = (await readFile(schemaFile, "utf8")).replace(HEADER, "");
await writeFile(
  schemaFile,
  HEADER +
    source
      .replaceAll(".default(')", ".default('')")
      .replace(/\.default\(\[\s*["']{2}\s*\]\)/g, ".default([])"),
);

await rm(path.join(dir, "meta"), { recursive: true, force: true });
for (const file of await readdir(dir)) {
  if (file !== "schema.ts") await rm(path.join(dir, file));
}
